language: node_js
node_js:
 - "10.17.0"
branches:
  only:
    - master
before_deploy:
  - node ./scripts/create-buckets.js mariafisher.dbknews.com
  - npm run build
deploy:
  - provider: s3
    access_key_id: "${AWS_KEY}"
    secret_access_key: ${AWS_SECRET}
    bucket: "mariafisher.dbknews.com"
    acl: public_read
    local_dir: build
    skip_cleanup: true
    on:
      all_branches: true
after_deploy:
  - echo "Static site deployed"